include("${CMAKE_CURRENT_LIST_DIR}/ReadCharacterProgram.cmake")
if(NOT DEFINED PAC_ROOT)
    message(FATAL_ERROR "PAC_ROOT is required")
endif()

set(GL_PATH "${PAC_ROOT}/src/game/render/materials/character/opengl_declarations.glsl")
set(D3D_PATH "${PAC_ROOT}/src/game/render/materials/character/d3d12_declarations.hlsl")
set(VK_PATH "${PAC_ROOT}/src/game/render/materials/character/character_lighting.glsl")

foreach(SOURCE_PATH IN ITEMS "${GL_PATH}" "${D3D_PATH}" "${VK_PATH}")
    read_character_program("${SOURCE_PATH}" SOURCE_TEXT)
    if(NOT SOURCE_TEXT MATCHES "sampleStageReflectionProbe")
        message(FATAL_ERROR "Z-A local-reflection sampler is missing from ${SOURCE_PATH}")
    endif()
    if(NOT SOURCE_TEXT MATCHES "faceSize \\* 4.*- 2")
        message(FATAL_ERROR "Z-A all-mip atlas qualification is missing from ${SOURCE_PATH}")
    endif()
    if(NOT SOURCE_TEXT MATCHES "mipStripY")
        message(FATAL_ERROR "Z-A authored mip-strip addressing is missing from ${SOURCE_PATH}")
    endif()
    if(NOT SOURCE_TEXT MATCHES "reflectionBlur \\+ max.*[Tt]extureDetailLodBias")
        message(FATAL_ERROR "Z-A ReflectionsBlur/quality LOD bridge is missing from ${SOURCE_PATH}")
    endif()
endforeach()

message(STATUS "Z-A local reflection probe contract verified")
