include("${CMAKE_CURRENT_LIST_DIR}/ReadCharacterProgram.cmake")
if(NOT DEFINED PAC_ROOT)
    message(FATAL_ERROR "PAC_ROOT is required")
endif()

set(GL_PATH "${PAC_ROOT}/src/game/render/materials/character/opengl_declarations.glsl")
set(D3D_PATH "${PAC_ROOT}/src/game/render/materials/character/d3d12_declarations.hlsl")
set(VK_MATERIAL_PATH "${PAC_ROOT}/src/game/render/materials/character/character_lighting.glsl")
set(VK_DIRECT_PATH "${PAC_ROOT}/src/game/render/materials/character/world_evaluation.glsl")
set(VK_INDIRECT_PATH "${PAC_ROOT}/src/game/render/materials/character/world_indirect_evaluation.glsl")

foreach(SOURCE_PATH IN ITEMS "${GL_PATH}" "${D3D_PATH}" "${VK_MATERIAL_PATH}")
    read_character_program("${SOURCE_PATH}" SOURCE_TEXT)
    if(NOT SOURCE_TEXT MATCHES "Exact SV SSS variation 56 samples diffuse irradiance")
        message(FATAL_ERROR "SV SSS source-role boundary is missing from ${SOURCE_PATH}")
    endif()
    if(NOT SOURCE_TEXT MATCHES "environmentDiffuse = sampleNeutralEnvironment")
        message(FATAL_ERROR "SV SSS diffuse-irradiance bridge is missing from ${SOURCE_PATH}")
    endif()
    if(NOT SOURCE_TEXT MATCHES "reflection = reflect" OR
       NOT SOURCE_TEXT MATCHES "-viewDirection")
        message(FATAL_ERROR "SV SSS reflection-vector bridge is missing from ${SOURCE_PATH}")
    endif()
    if(NOT SOURCE_TEXT MATCHES "environmentSpecular = sampleNeutralEnvironment")
        message(FATAL_ERROR "SV SSS roughness-filtered specular bridge is missing from ${SOURCE_PATH}")
    endif()
    if(NOT SOURCE_TEXT MATCHES "neutralFill =")
        message(FATAL_ERROR "SV SSS neutral review-light fill is missing from ${SOURCE_PATH}")
    endif()
    if(SOURCE_TEXT MATCHES "0\\.34f? \\+ 0\\.78f? \\* wrappedNdotL")
        message(FATAL_ERROR "SV SSS regressed to the flat ambient approximation in ${SOURCE_PATH}")
    endif()
    if(NOT SOURCE_TEXT MATCHES "fibreSheen = fibreSurface" OR
       NOT SOURCE_TEXT MATCHES "qualityDetail \\* wrappedNdotL")
        message(FATAL_ERROR "The bounded Eevee fibre approximation changed in ${SOURCE_PATH}")
    endif()
endforeach()

foreach(SOURCE_PATH IN ITEMS "${VK_DIRECT_PATH}" "${VK_INDIRECT_PATH}")
    read_character_program("${SOURCE_PATH}" SOURCE_TEXT)
    if(NOT SOURCE_TEXT MATCHES "evaluateSubsurfaceSurface")
        message(FATAL_ERROR "Vulkan SSS call is missing from ${SOURCE_PATH}")
    endif()
    if(SOURCE_PATH STREQUAL VK_DIRECT_PATH)
        set(EXPECTED_ENVIRONMENT_ARGUMENT "                environmentTexture,")
    else()
        set(EXPECTED_ENVIRONMENT_ARGUMENT "                environmentTextures[nonuniformEXT(materialIndex)],")
    endif()
    string(FIND "${SOURCE_TEXT}" "${EXPECTED_ENVIRONMENT_ARGUMENT}" ENVIRONMENT_ARGUMENT_POSITION)
    if(ENVIRONMENT_ARGUMENT_POSITION EQUAL -1)
        message(FATAL_ERROR "Vulkan SSS call does not supply the shared environment in ${SOURCE_PATH}")
    endif()
endforeach()

message(STATUS "SV native SSS environment contract verified")
