"""Restore original Kanto card scans and verify authored card/portrait UV windows."""
from pathlib import Path, PurePosixPath
import argparse
import collections
import hashlib
import json
import re
import struct
import urllib.request

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / 'config/ui/pokemon_card_art.json'
HEADER = ROOT / 'src/game/runtime/ui/PokemonArtworkData.h'
MEW_URL = 'https://pkmncards.com/wp-content/uploads/mew-wizards-black-star-promos-8.jpg'


def contains(outer, inner):
    x, y, w, h = outer
    a, b, c, d = inner
    return x <= a and y <= b and a + c <= x + w and b + d <= y + h


def overlaps(a, b):
    x, y, w, h = a
    u, v, s, t = b
    return x < u + s and u < x + w and y < v + t and v < y + h


def validate(manifest):
    rows = manifest['cards']
    if manifest['schema'] != 1 or [r['dex'] for r in rows] != list(range(1, 152)):
        raise ValueError('Expected each Kanto dex ID once, in order.')
    expected_sets = {'base-set': 69, 'jungle': 45, 'fossil': 36, 'wizards-black-star-promos': 1}
    if collections.Counter(r['set'] for r in rows) != expected_sets:
        raise ValueError('Unexpected original-set coverage.')
    names = set()
    for row in rows:
        species = row['species']
        key = re.sub('[^a-z0-9]', '', species)
        if not re.fullmatch(r'[a-z][a-z_-]+', species) or key in names:
            raise ValueError('Invalid or ambiguous species identity.')
        names.add(key)
        if row['path'] != f"assets/ui/pokemon/tcg/{row['dex']:03d}.jpg":
            raise ValueError('Unexpected runtime destination.')
        if not re.fullmatch('[a-f0-9]{64}', row['sha256']) or type(row['bytes']) is not int or row['bytes'] <= 0:
            raise ValueError('Invalid original scan digest or size.')
        if not re.fullmatch(r'\d+', row['number']):
            raise ValueError('A card collector number is required.')
        w, h = row['width'], row['height']
        if any(type(v) is not int or v <= 0 for v in (w, h)):
            raise ValueError('Invalid scan dimensions.')
        portrait = row['portrait']
        if len(portrait) != 3 or portrait[2] < 48:
            raise ValueError('Invalid portrait square.')
        portrait_rect = [*portrait[:2], portrait[2], portrait[2]]
        for rect in (row['illustration'], row['art'], portrait_rect):
            if len(rect) != 4 or any(type(v) is not int for v in rect) or min(rect[2:]) <= 0:
                raise ValueError('Invalid integer crop window.')
            if not contains([0, 0, w, h], rect):
                raise ValueError(f'Crop escapes scan: {species}')
        for rect in (row['art'], portrait_rect):
            if not contains(row['illustration'], rect) or overlaps(rect, row.get('excluded_badge', [0, 0, 0, 0])):
                raise ValueError(f'Crop includes card labels or badge: {species}')
        source = row['source']
        if row['dex'] == 151:
            if source['kind'] != 'web' or source['url'] != MEW_URL or row['number'] != '8':
                raise ValueError('Mew must use the original promo 8 scan.')
        else:
            source_path = PurePosixPath(source['path'])
            if source['kind'] != 'binderledger' or source_path.parent != PurePosixPath('data/card-images'):
                raise ValueError('Unexpected BinderLedger source path.')
            if not source_path.name.startswith(f"pokemon-{row['set']}-") or source_path.suffix != '.jpg':
                raise ValueError('Scan does not belong to the recorded set.')
    return rows


def generated_header(rows):
    lines = ['// Generated by tools/assets/restore_pokemon_card_art.py --write-header.',
             '// Edit config/ui/pokemon_card_art.json, then regenerate.',
             '#pragma once', '#include <array>', '#include <string_view>', '',
             'namespace game::runtime::pokemon_artwork {',
             'struct PixelRect { int x, y, w, h; };',
             'struct Entry {', '    std::string_view species;', '    int dex;',
             '    int width, height;', '    PixelRect art;', '    PixelRect portrait;', '};',
             'inline constexpr std::array<Entry, 151> entries{{']
    for row in rows:
        art = ', '.join(map(str, row['art']))
        x, y, size = row['portrait']
        lines.append(f'    {{"{row["species"]}", {row["dex"]}, {row["width"]}, {row["height"]}, {{{art}}}, {{{x}, {y}, {size}, {size}}}}},')
    return '\n'.join(lines + ['}};', '} // namespace game::runtime::pokemon_artwork', ''])


def image_dimensions(data):
    if data[:8] == b'\x89PNG\r\n\x1a\n':
        return struct.unpack('>II', data[16:24])
    if data[:2] != b'\xff\xd8':
        raise ValueError('Expected original JPEG or PNG scan.')
    pos = 2
    while pos < len(data):
        if data[pos] != 255:
            raise ValueError('Invalid JPEG marker.')
        while data[pos] == 255:
            pos += 1
        marker = data[pos]
        pos += 1
        length = int.from_bytes(data[pos:pos + 2], 'big')
        if marker in (0xc0, 0xc1, 0xc2):
            h, w = struct.unpack('>HH', data[pos + 3:pos + 7])
            return w, h
        if length < 2:
            break
        pos += length
    raise ValueError('Missing JPEG dimensions.')


def verify_scan(data, row):
    if len(data) != row['bytes'] or hashlib.sha256(data).hexdigest() != row['sha256']:
        raise ValueError(f'Original scan changed: {row["species"]}')
    if image_dimensions(data) != (row['width'], row['height']):
        raise ValueError(f'Scan dimensions changed: {row["species"]}')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--verify-only', action='store_true', help='Offline verification; do not copy or download.')
    parser.add_argument('--write-header', action='store_true', help='Regenerate the runtime table after framing edits.')
    parser.add_argument('--binderledger-root', type=Path, help='Optional source catalog checkout for first-time restoration.')
    parser.add_argument('--depot-runtime', type=Path, help='Restore from, publish to, or verify the private runtime copy.')
    args = parser.parse_args()
    rows = validate(json.loads(MANIFEST.read_text(encoding='utf-8-sig')))
    expected = generated_header(rows)
    if args.write_header:
        HEADER.write_text(expected, encoding='utf-8')
    elif not HEADER.is_file() or HEADER.read_text(encoding='utf-8') != expected:
        raise ValueError('Runtime table is stale. Run with --write-header.')
    for row in rows:
        path = ROOT / row['path']
        depot = args.depot_runtime.resolve() / row['path'] if args.depot_runtime else None
        if path.is_file():
            data = path.read_bytes()
        elif args.verify_only:
            raise FileNotFoundError(path)
        elif depot and depot.is_file():
            data = depot.read_bytes()
        elif row['source']['kind'] == 'binderledger' and args.binderledger_root:
            data = (args.binderledger_root.resolve() / row['source']['path']).read_bytes()
        elif row['source']['kind'] == 'web':
            with urllib.request.urlopen(row['source']['url'], timeout=40) as response:
                data = response.read()
        else:
            raise FileNotFoundError(f'Missing {row["species"]}; supply --depot-runtime or --binderledger-root.')
        verify_scan(data, row)
        if not path.is_file():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
        if depot:
            if depot.is_file():
                verify_scan(depot.read_bytes(), row)
            elif args.verify_only:
                raise FileNotFoundError(depot)
            else:
                depot.parent.mkdir(parents=True, exist_ok=True)
                depot.write_bytes(data)
    print('Verified 151 original card scans, hashes, card/portrait crops and runtime table.')


if __name__ == '__main__':
    main()
