"""Restore pinned, unmodified HOME PNGs and verify the generated runtime framing table."""
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor
import argparse
import hashlib
import json
import re
import struct
import urllib.request

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / 'config/ui/pokemon_home_portraits.json'
HEADER = ROOT / 'src/game/runtime/ui/PokemonPortraitData.h'


def validate(manifest):
    entries = manifest['portraits']
    if manifest['schema'] != 1 or [e['dex'] for e in entries] != list(range(1, 152)):
        raise ValueError('Portrait manifest must contain each Kanto dex ID once, in order.')
    if (manifest['width'], manifest['height']) != (512, 512):
        raise ValueError('Expected original 512x512 HOME images.')
    commit = manifest['source_commit']
    if not re.fullmatch(r'[a-f0-9]{40}', commit):
        raise ValueError('Source must be pinned to a Git commit.')
    names = set()
    for entry in entries:
        dex = entry['dex']
        key = re.sub(r'[^a-z0-9]', '', entry['species'])
        if not re.fullmatch(r'[a-z][a-z_-]+', entry['species']) or key in names:
            raise ValueError('Invalid or ambiguous species identity.')
        names.add(key)
        if entry['path'] != f'assets/ui/pokemon/home/{dex:03d}.png':
            raise ValueError('Unexpected portrait destination.')
        expected_url = f'https://raw.githubusercontent.com/PokeAPI/sprites/{commit}/sprites/pokemon/other/home/{dex}.png'
        if entry['url'] != expected_url or not re.fullmatch(r'[a-f0-9]{64}', entry['sha256']):
            raise ValueError('Unexpected portrait source or digest.')
        x, y, size = entry['crop']
        if any(type(v) is not int for v in (x, y, size)) or min(x, y) < 0 or not 128 <= size <= 512 or max(x, y) + size > 512:
            raise ValueError(f'Invalid square face crop: {entry["species"]}')
    return entries


def generated_header(entries):
    lines = ['// Generated by tools/assets/restore_home_portraits.py --write-header.',
             '// Edit framing/provenance in config/ui/pokemon_home_portraits.json.',
             '#pragma once', '#include <array>', '#include <string_view>', '',
             'namespace game::runtime::pokemon_portraits {',
             'struct Entry {', '    std::string_view species;', '    int dex;',
             '    int cropX, cropY, cropSize;', '};',
             'inline constexpr std::array<Entry, 151> entries{{']
    for entry in entries:
        x, y, size = entry['crop']
        lines.append(f'    {{"{entry["species"]}", {entry["dex"]}, {x}, {y}, {size}}},')
    lines += ['}};', '} // namespace game::runtime::pokemon_portraits', '']
    return '\n'.join(lines)


def verify_png(data, entry):
    if len(data) != entry['bytes'] or hashlib.sha256(data).hexdigest() != entry['sha256']:
        raise ValueError(f'Portrait differs from recorded original: {entry["species"]}')
    if data[:8] != b'\x89PNG\r\n\x1a\n' or struct.unpack('>II', data[16:24]) != (512, 512) or data[25] != 6:
        raise ValueError('Expected 512x512 RGBA PNG.')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--verify-only', action='store_true', help='Offline checks; never downloads.')
    parser.add_argument('--write-header', action='store_true', help='Regenerate C++ table after editing crops.')
    parser.add_argument('--depot-runtime', type=Path, help='Also publish originals under this private runtime root.')
    args = parser.parse_args()
    entries = validate(json.loads(MANIFEST.read_text(encoding='utf-8-sig')))
    expected = generated_header(entries)
    if args.write_header:
        HEADER.write_text(expected, encoding='utf-8')
    elif not HEADER.is_file() or HEADER.read_text(encoding='utf-8') != expected:
        raise ValueError('Runtime portrait table is stale. Run with --write-header.')

    def restore(entry):
        path = ROOT / entry['path']
        if path.is_file():
            data = path.read_bytes()
        else:
            if args.verify_only:
                raise FileNotFoundError(f'Missing HOME portrait: {entry["species"]}')
            request = urllib.request.Request(entry['url'], headers={'User-Agent': 'PokemonAutochess-AssetRestore'})
            with urllib.request.urlopen(request, timeout=45) as response:
                data = response.read()
        # Validate before publishing; never replace a mismatched existing asset.
        verify_png(data, entry)
        if not path.is_file():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
        if args.depot_runtime:
            depot_path = args.depot_runtime.resolve() / entry['path']
            if depot_path.is_file():
                verify_png(depot_path.read_bytes(), entry)
            elif args.verify_only:
                raise FileNotFoundError(depot_path)
            else:
                depot_path.parent.mkdir(parents=True, exist_ok=True)
                depot_path.write_bytes(data)

    with ThreadPoolExecutor(max_workers=8) as pool:
        list(pool.map(restore, entries))
    print('Verified all 151 original HOME portraits, source hashes, square framing and runtime table.')


if __name__ == '__main__':
    main()
