#include "game/editor/PokemonAutochessEditorPreviewCatalog.h"

#include <algorithm>

namespace game::editor::preview_catalog {

namespace {

constexpr Definitions kDefinitions{{
    {
        "route1-pilot-planning",
        "Planning",
        "Starting setups",
        "Place Pokemon on the current South Entrance board before combat.",
        "route_planning",
        "classic",
        "scripts/states/route1_pilot.lua",
        "routes/route1-pilot",
    },
    {
        "route1-pilot-battle",
        "Battle",
        "Starting setups",
        "Start a battle on the current South Entrance map.",
        "route_battle",
        "classic",
        "scripts/states/route1_pilot.lua",
        "routes/route1-pilot",
    },
    {
        "route1-pilot-crowded",
        "Crowded Battle",
        "Starting setups",
        "Press Play: a matched 12-Pokemon battle for terrain and combat readability comparison.",
        "snapshot",
        "classic",
        "config/debug/editor_route1_pilot_comparison.json",
        "routes/route1-pilot",
    },
    {
        "route1-pilot-grass",
        "Grass Test",
        "Tests",
        "Opposing Pokemon start in separate grass patches. Play to watch searching, local rustling and attack reveals. F10 toggles concealed units for debugging.",
        "snapshot",
        "classic",
        "config/debug/editor_route1_pilot_grass.json",
        "routes/route1-pilot",
    },
    {
        "route1-pilot-ledges",
        "Ledge Test",
        "Tests",
        "Bulbasaur and Rattata start above the ledge; Charmander starts below. Press Play to watch the one-way jumps.",
        "snapshot",
        "classic",
        "config/debug/editor_route1_pilot_ledges.json",
        "routes/route1-pilot",
    },
    {
        "route1-pilot-travel",
        "Travel Test",
        "Tests",
        "Press Play: recall the team, travel to South Clearing, then send it out in the same formation. R travels back after arrival. Board and bench placements remain editable after arrival.",
        "snapshot",
        "classic",
        "config/debug/editor_route1_pilot_travel.json",
        "routes/route1-pilot",
    },
    {
        "route1-pilot-earthquake",
        "Earthquake Comparison",
        "Tests",
        "Press Play: the same 12-Pokemon battle with one broad Earthquake, then two overlapping effects. Visual experiment only; Earthquake adds no damage.",
        "snapshot",
        "classic",
        "config/debug/editor_route1_pilot_earthquake_comparison.json",
        "routes/route1-pilot",
    },
    {
        "route1-south-clearing-planning",
        "Planning",
        "Starting setups",
        "Place Pokemon on the Blender-authored South Clearing. The east grass bed provides concealment; the north ledge and wide southern ramp retain the source layout.",
        "route_planning",
        "classic",
        "scripts/states/route1_south_clearing.lua",
        "routes/route1-south-clearing",
    },
    {
        "route1-south-clearing-battle",
        "Battle",
        "Starting setups",
        "Start a battle on the Blender-authored South Clearing with directional ledges, encounter grass and enemy memory.",
        "route_battle",
        "classic",
        "scripts/states/route1_south_clearing.lua",
        "routes/route1-south-clearing",
    },
    {
        "route1-south-clearing-grass",
        "Grass Test",
        "Tests",
        "Bulbasaur crosses the large east grass bed to pursue Rattata. Play to watch the blades part, rustle and spring back. F10 shows concealed units for debugging.",
        "snapshot",
        "classic",
        "config/debug/editor_route1_south_clearing_grass.json",
        "routes/route1-south-clearing",
    },
    {
        "route1-north-terraces-planning",
        "Planning",
        "Starting setups",
        "Place Pokemon on the third Route 1 arena, nine tiles north of South Clearing, with an open board, corner ramps and the original east grass bed.",
        "route_planning",
        "classic",
        "scripts/states/route1_north_terraces.lua",
        "routes/route1-north-terraces",
    },
    {
        "route1-north-terraces-battle",
        "Battle",
        "Starting setups",
        "Start a battle farther up Route 1 using directional ledges, full-size encounter grass and enemy memory.",
        "route_battle",
        "classic",
        "scripts/states/route1_north_terraces.lua",
        "routes/route1-north-terraces",
    },
    {
        "route1-north-terraces-grass",
        "Grass Test",
        "Tests",
        "Bulbasaur starts in the east grass bed while Rattata patrols the upper lawn. Play to inspect concealment, rustling and the intervening ledges.",
        "snapshot",
        "classic",
        "config/debug/editor_route1_north_terraces_grass.json",
        "routes/route1-north-terraces",
    },
    {
        "route1-north-entrance-planning",
        "Planning",
        "Starting setups",
        "Place Pokemon on the centered northern Route 1 board, with four rows on each terrace, a broad grass bed and clear dirt benches. The original ramp sits beside the board.",
        "route_planning",
        "classic",
        "scripts/states/route1_north_entrance.lua",
        "routes/route1-north-entrance",
    },
    {
        "route1-north-entrance-battle",
        "Battle",
        "Starting setups",
        "Start a battle on the final Route 1 arena with directional ledges, encounter grass and enemy memory.",
        "route_battle",
        "classic",
        "scripts/states/route1_north_entrance.lua",
        "routes/route1-north-entrance",
    },
    {
        "route1-north-entrance-grass",
        "Grass Test",
        "Tests",
        "Bulbasaur starts in the lower grass bed while Rattata searches the upper terrace. Play to inspect concealment, rustling and southbound ledge jumps.",
        "snapshot",
        "classic",
        "config/debug/editor_route1_north_entrance_grass.json",
        "routes/route1-north-entrance",
    },
    {
        "route1-flat-experiment-planning",
        "Planning",
        "Starting setups",
        "Place Pokemon on a flat dirt clearing. Surrounding Route 1 scenery is retained; combat has no ledges or encounter grass.",
        "route_planning",
        "classic",
        "scripts/states/route1_flat_experiment.lua",
        "routes/route1-flat-experiment",
    },
    {
        "route1-flat-experiment-crowded",
        "Crowded Battle",
        "Starting setups",
        "Press Play: a matched 12-Pokemon battle for terrain and combat readability comparison.",
        "snapshot",
        "classic",
        "config/debug/editor_route1_flat_experiment_comparison.json",
        "routes/route1-flat-experiment",
    },
    {
        "route1-flat-experiment-round-end",
        "Round Transition Test",
        "Tests",
        "Press Play: finish a real round, recall the team, throw their balls back to the saved formation, then open the shop on the retained flat arena.",
        "snapshot",
        "classic",
        "config/debug/editor_route1_flat_round_end.json",
        "routes/route1-flat-experiment",
    },
    {
        "route1-flat-experiment-hud",
        "HUD Inspection Test",
        "Tests",
        "A planning shop with Bulbasaur selected. Right-click a Pokemon to inspect it without moving it; 0 clears selection.",
        "snapshot",
        "classic",
        "config/debug/editor_hud_inspection.json",
        "routes/route1-flat-experiment",
    },
    {
        "route1-flat-experiment-earthquake",
        "Earthquake Comparison",
        "Tests",
        "Press Play: the same 12-Pokemon battle with one broad Earthquake, then two overlapping effects. Visual experiment only; Earthquake adds no damage.",
        "snapshot",
        "classic",
        "config/debug/editor_route1_flat_experiment_earthquake_comparison.json",
        "routes/route1-flat-experiment",
    },
    {
        "boot",
        "Boot Sequence",
        "Menus",
        "Replay the loading presentation, then enter the main menu.",
        "main_menu",
        "classic",
        "",
    },
    {
        "main-menu",
        "Main Menu",
        "Menus",
        "Open the Classic / Adventure frontend without restarting the runtime.",
        "main_menu",
        "classic",
        "",
    },
    {
        "starter-classic",
        "Starter Selection - Classic",
        "Oak's Lab",
        "Choose a starter in Oak's Lab, then enter the Flat Dirt Experiment in Classic mode.",
        "starter",
        "classic",
        "",
    },
    {
        "starter-adventure",
        "Starter Selection - Adventure",
        "Oak's Lab",
        "Choose a starter in Oak's Lab, then enter the Flat Dirt Experiment in Adventure mode.",
        "starter",
        "adventure",
        "",
    },
}};

} // namespace

const Definitions& all() noexcept {
    return kDefinitions;
}

const Definition* find(std::string_view id) noexcept {
    const auto found = std::find_if(
        kDefinitions.begin(),
        kDefinitions.end(),
        [id](const Definition& definition) {
            return id == definition.id;
        });
    return found == kDefinitions.end() ? nullptr : &*found;
}

} // namespace game::editor::preview_catalog
