#include "game/editor/PokemonAutochessEditorPreviewCatalog.h"

#include <algorithm>

namespace game::editor::preview_catalog {

namespace {

constexpr Definitions kDefinitions{{
    {
        "route1-pilot-grass",
        "Grass Test",
        "South Entrance",
        "Opposing Pokemon start in separate grass patches. Play to watch searching, local rustling and attack reveals. F10 toggles concealed units for debugging.",
        "snapshot",
        "classic",
        "config/debug/editor_route1_pilot_grass.json",
        "routes/route1-pilot",
    },
    {
        "route1-pilot-ledges",
        "Ledge Test",
        "South Entrance",
        "Bulbasaur and Rattata start above the ledge; Charmander starts below. Press Play to watch the one-way jumps.",
        "snapshot",
        "classic",
        "config/debug/editor_route1_pilot_ledges.json",
        "routes/route1-pilot",
    },
    {
        "route1-pilot-planning",
        "Planning",
        "South Entrance",
        "Place Pokemon on the current South Entrance board before combat.",
        "route_planning",
        "classic",
        "scripts/states/route1_pilot.lua",
        "routes/route1-pilot",
    },
    {
        "route1-pilot-battle",
        "Battle",
        "South Entrance",
        "Start a battle on the current South Entrance map.",
        "route_battle",
        "classic",
        "scripts/states/route1_pilot.lua",
        "routes/route1-pilot",
    },
    {
        "route1-south-clearing-grass",
        "Grass Test",
        "South Clearing",
        "Bulbasaur crosses the large east grass bed to pursue Rattata. Play to watch the blades part, rustle and spring back. F10 shows concealed units for debugging.",
        "snapshot",
        "classic",
        "config/debug/editor_route1_south_clearing_grass.json",
        "routes/route1-south-clearing",
    },
    {
        "route1-south-clearing-planning",
        "Planning",
        "South Clearing",
        "Place Pokemon on the Blender-authored South Clearing. The east grass bed provides concealment; the north ledge and wide southern ramp retain the source layout.",
        "route_planning",
        "classic",
        "scripts/states/route1_south_clearing.lua",
        "routes/route1-south-clearing",
    },
    {
        "route1-south-clearing-battle",
        "Battle",
        "South Clearing",
        "Start a battle on the Blender-authored South Clearing with directional ledges, encounter grass and enemy memory.",
        "route_battle",
        "classic",
        "scripts/states/route1_south_clearing.lua",
        "routes/route1-south-clearing",
    },
    {
        "route1-north-terraces-grass",
        "Grass Test",
        "North Terraces",
        "Bulbasaur starts in the east grass bed while Rattata patrols the upper lawn. Play to inspect concealment, rustling and the intervening ledges.",
        "snapshot",
        "classic",
        "config/debug/editor_route1_north_terraces_grass.json",
        "routes/route1-north-terraces",
    },
    {
        "route1-north-terraces-planning",
        "Planning",
        "North Terraces",
        "Place Pokemon on the third Route 1 arena, nine tiles north of South Clearing, with an open board, corner ramps and the original east grass bed.",
        "route_planning",
        "classic",
        "scripts/states/route1_north_terraces.lua",
        "routes/route1-north-terraces",
    },
    {
        "route1-north-terraces-battle",
        "Battle",
        "North Terraces",
        "Start a battle farther up Route 1 using directional ledges, full-size encounter grass and enemy memory.",
        "route_battle",
        "classic",
        "scripts/states/route1_north_terraces.lua",
        "routes/route1-north-terraces",
    },
    {
        "route1-north-entrance-grass",
        "Grass Test",
        "North Entrance",
        "Bulbasaur starts in the lower grass bed while Rattata searches the upper terrace. Play to inspect concealment, rustling and southbound ledge jumps.",
        "snapshot",
        "classic",
        "config/debug/editor_route1_north_entrance_grass.json",
        "routes/route1-north-entrance",
    },
    {
        "route1-north-entrance-planning",
        "Planning",
        "North Entrance",
        "Place Pokemon on the centered northern Route 1 board, with four rows on each terrace, a broad grass bed and clear dirt benches. The original ramp sits beside the board.",
        "route_planning",
        "classic",
        "scripts/states/route1_north_entrance.lua",
        "routes/route1-north-entrance",
    },
    {
        "route1-north-entrance-battle",
        "Battle",
        "North Entrance",
        "Start a battle on the final Route 1 arena with directional ledges, encounter grass and enemy memory.",
        "route_battle",
        "classic",
        "scripts/states/route1_north_entrance.lua",
        "routes/route1-north-entrance",
    },
    {
        "boot",
        "Boot Sequence",
        "Frontend",
        "Replay the loading presentation, then enter the main menu.",
        "main_menu",
        "classic",
        "",
    },
    {
        "main-menu",
        "Main Menu",
        "Frontend",
        "Open the Classic / Adventure frontend without restarting the runtime.",
        "main_menu",
        "classic",
        "",
    },
    {
        "starter-classic",
        "Starter Selection - Classic",
        "Starter Selection",
        "Choose a starter in Oak's Lab in Classic mode. Frontend backdrop only.",
        "starter",
        "classic",
        "",
    },
    {
        "starter-adventure",
        "Starter Selection - Adventure",
        "Starter Selection",
        "Choose a starter in Oak's Lab in Adventure mode. Frontend backdrop only.",
        "starter",
        "adventure",
        "",
    },
    {
        "route1-planning-classic",
        "Route 1 Planning - Classic",
        "Route 1",
        "Restore Route 1 in its Classic planning phase.",
        "snapshot",
        "classic",
        "config/debug/editor_route1_planning.json",
        "routes/route1",
    },
    {
        "route1-planning-adventure",
        "Route 1 Planning - Adventure",
        "Route 1",
        "Restore Route 1 in its Adventure planning phase.",
        "snapshot",
        "adventure",
        "config/debug/editor_route1_planning.json",
        "routes/route1",
    },
    {
        "route1-battle-classic",
        "Route 1 Battle - Classic",
        "Route 1",
        "Restore the deterministic Route 1 battle in Classic mode.",
        "snapshot",
        "classic",
        "config/debug/debug_state_snapshot_bulbasaur_route1_combat.json",
        "routes/route1",
    },
    {
        "route1-battle-adventure",
        "Route 1 Battle - Adventure",
        "Route 1",
        "Restore the deterministic Route 1 battle in Adventure mode.",
        "snapshot",
        "adventure",
        "config/debug/debug_state_snapshot_bulbasaur_route1_combat.json",
        "routes/route1",
    },
    {
        "route1-5-planning-classic",
        "Route 1.5 Planning - Classic",
        "Route 1.5",
        "Open the Route 1.5 planning phase in Classic mode.",
        "route_planning",
        "classic",
        "scripts/states/route1_5.lua",
        "routes/route1-5",
    },
    {
        "route1-5-planning-adventure",
        "Route 1.5 Planning - Adventure",
        "Route 1.5",
        "Open the Route 1.5 planning phase in Adventure mode.",
        "route_planning",
        "adventure",
        "scripts/states/route1_5.lua",
        "routes/route1-5",
    },
    {
        "route1-5-battle-classic",
        "Route 1.5 Battle - Classic",
        "Route 1.5",
        "Open the Route 1.5 battle phase in Classic mode.",
        "route_battle",
        "classic",
        "scripts/states/route1_5.lua",
        "routes/route1-5",
    },
    {
        "route1-5-battle-adventure",
        "Route 1.5 Battle - Adventure",
        "Route 1.5",
        "Open the Route 1.5 battle phase in Adventure mode.",
        "route_battle",
        "adventure",
        "scripts/states/route1_5.lua",
        "routes/route1-5",
    },
    {
        "route22-planning-classic",
        "Route 22 Planning - Classic",
        "Route 22",
        "Open the Route 22 planning phase in Classic mode.",
        "route_planning",
        "classic",
        "scripts/states/route22.lua",
        "routes/route22",
    },
    {
        "route22-planning-adventure",
        "Route 22 Planning - Adventure",
        "Route 22",
        "Open the Route 22 planning phase in Adventure mode.",
        "route_planning",
        "adventure",
        "scripts/states/route22.lua",
        "routes/route22",
    },
    {
        "route22-battle-classic",
        "Route 22 Battle - Classic",
        "Route 22",
        "Open the Route 22 battle phase in Classic mode.",
        "route_battle",
        "classic",
        "scripts/states/route22.lua",
        "routes/route22",
    },
    {
        "route22-battle-adventure",
        "Route 22 Battle - Adventure",
        "Route 22",
        "Open the Route 22 battle phase in Adventure mode.",
        "route_battle",
        "adventure",
        "scripts/states/route22.lua",
        "routes/route22",
    },
    {
        "route2-planning-classic",
        "Route 2 Planning - Classic",
        "Route 2",
        "Open the Route 2 planning phase in Classic mode.",
        "route_planning",
        "classic",
        "scripts/states/route2.lua",
        "routes/route2",
    },
    {
        "route2-planning-adventure",
        "Route 2 Planning - Adventure",
        "Route 2",
        "Open the Route 2 planning phase in Adventure mode.",
        "route_planning",
        "adventure",
        "scripts/states/route2.lua",
        "routes/route2",
    },
    {
        "route2-battle-classic",
        "Route 2 Battle - Classic",
        "Route 2",
        "Open the Route 2 battle phase in Classic mode.",
        "route_battle",
        "classic",
        "scripts/states/route2.lua",
        "routes/route2",
    },
    {
        "route2-battle-adventure",
        "Route 2 Battle - Adventure",
        "Route 2",
        "Open the Route 2 battle phase in Adventure mode.",
        "route_battle",
        "adventure",
        "scripts/states/route2.lua",
        "routes/route2",
    },
    {
        "viridian-forest-planning-classic",
        "Viridian Forest Planning - Classic",
        "Viridian Forest",
        "Open the Viridian Forest planning phase in Classic mode.",
        "route_planning",
        "classic",
        "scripts/states/viridian_forest.lua",
        "routes/viridian-forest",
    },
    {
        "viridian-forest-planning-adventure",
        "Viridian Forest Planning - Adventure",
        "Viridian Forest",
        "Open the Viridian Forest planning phase in Adventure mode.",
        "route_planning",
        "adventure",
        "scripts/states/viridian_forest.lua",
        "routes/viridian-forest",
    },
    {
        "viridian-forest-battle-classic",
        "Viridian Forest Battle - Classic",
        "Viridian Forest",
        "Open the Viridian Forest battle phase in Classic mode.",
        "route_battle",
        "classic",
        "scripts/states/viridian_forest.lua",
        "routes/viridian-forest",
    },
    {
        "viridian-forest-battle-adventure",
        "Viridian Forest Battle - Adventure",
        "Viridian Forest",
        "Open the Viridian Forest battle phase in Adventure mode.",
        "route_battle",
        "adventure",
        "scripts/states/viridian_forest.lua",
        "routes/viridian-forest",
    },
    {
        "route3-planning-classic",
        "Route 3 Planning - Classic",
        "Route 3",
        "Open the Route 3 planning phase in Classic mode.",
        "route_planning",
        "classic",
        "scripts/states/route3.lua",
        "routes/route3",
    },
    {
        "route3-planning-adventure",
        "Route 3 Planning - Adventure",
        "Route 3",
        "Open the Route 3 planning phase in Adventure mode.",
        "route_planning",
        "adventure",
        "scripts/states/route3.lua",
        "routes/route3",
    },
    {
        "route3-battle-classic",
        "Route 3 Battle - Classic",
        "Route 3",
        "Open the Route 3 battle phase in Classic mode.",
        "route_battle",
        "classic",
        "scripts/states/route3.lua",
        "routes/route3",
    },
    {
        "route3-battle-adventure",
        "Route 3 Battle - Adventure",
        "Route 3",
        "Open the Route 3 battle phase in Adventure mode.",
        "route_battle",
        "adventure",
        "scripts/states/route3.lua",
        "routes/route3",
    },
}};

} // namespace

const Definitions& all() noexcept {
    return kDefinitions;
}

const Definition* find(std::string_view id) noexcept {
    const auto found = std::find_if(
        kDefinitions.begin(),
        kDefinitions.end(),
        [id](const Definition& definition) {
            return id == definition.id;
        });
    return found == kDefinitions.end() ? nullptr : &*found;
}

} // namespace game::editor::preview_catalog
