// MovementExecutor.h

#pragma once

#include "../../GameWorld.h"
#include "../../PokemonInstance.h"
#include <unordered_map>
#include <glm/glm.hpp>
#include "../../GridOccupancy.h"

// The MovementExecutor is responsible for updating unit positions
// based on the planned moves generated by MovementPlanner.
class MovementExecutor {
public:
    // Constructs the executor with access to the game world
    // and grid configuration.
    MovementExecutor(GameWorld* world, int gridCols, int gridRows, float cellSize);

    // Executes the movement for each unit using planned moves.
    // Returns the temporary grid occupancy map.
    GridOccupancy executeMoves(
        const std::unordered_map<PokemonInstance*, glm::ivec2>& plannedMoves,
        float deltaTime);

    // Updates each unit's rotation to face its nearest enemy.
    void updateUnitRotations();

    // Utility functions for coordinate conversion.
    glm::ivec2 worldToGrid(const glm::vec3& pos) const;
    glm::vec3 gridToWorld(int col, int row) const;
    uint32_t gridKey(int col, int row) const;
    bool isValidGridPosition(int col, int row) const;

private:
    GameWorld* gameWorld;
    int gridCols;
    int gridRows;
    float cellSize;
};
